---
application:
  OpenIDSecret: v03j1k9fp09zuvoj2o3jrasd8oxzjcvk3

framework:
  SiteConfig: etc/site_config.yml
  AdminMode: 0
  ApplicationClass: Retail
  ApplicationName: Retail
  ApplicationUUID: 7BA46032-74DB-11DD-A027-AFC80B18BD64
  ConfigFileVersion: 4
  Database:
    AutoUpgrade: 1
    CheckSchema: 1
    Database: retail
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.3
  DevelMode: 1
  L10N:
    PoDir: share/po
    AllowedLang:
      - en
      - zh_tw
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins:
    # - SinglePage: {}
    - I18N: {}
    - LetMe: {}
    - SkeletonApp: {}
    # - REST: {}
    # - Halo: {}
    # - ErrorTemplates: {}
    # - OnlineDocs: {}
    - CompressedCSSandJS: {}
    # - AdminUI: {}
    - LetMe: {}
    - User: {}
    - OpenID: {}

  PubSub:
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: Retail::View
  View:
    FallbackHandler: Jifty::View::Mason::Handler
    Handlers:
      - Jifty::View::Static::Handler
      - Jifty::View::Declare::Handler
      - Jifty::View::Mason::Handler
  Web:
    # ServerClass: Jifty::Server::Fork
    # SessionClass: Jifty::Web::Session::ClientSide
    # SessionSecret: '9jv3$9*!ufz239#$^'
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig:
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
